export enum EPartnerFields {
    id = 'number',
    name = 'string',
    display_name = 'string',
    parent_id = 'Array<number | string>',
    category_id = 'Array<number | string>',
    customer = 'boolean',
    supplier = 'boolean',
    street = 'boolean',
    street2 = 'boolean',
    zip = 'boolean',
    city = 'boolean',
    state_id = 'Array<number | string>',
    country_id = 'Array<number | string>',
    email = 'boolean',
    phone = 'boolean',
    mobile = 'boolean',
    company_name = 'string',
    ref = 'string',
}
